export const testChartData = {
    width: 600,
    height: 300,
    minY: 0,
    maxY: 400,
    margin: {
      top: 50,
      right: 110,
      bottom: 50,
      left: 60,
    },
    curve: "linear",
    axisTop: null,
    axisRight: null,
    axisBottom: {
      tickSize: 5,
      tickPadding: 5,
      tickRotation: 0,
      legend: "transportation",
      legendOffset: 36,
      legendPosition: "center",
    },
    axisLeft: {
      tickSize: 5,
      tickPadding: 5,
      tickRotation: 0,
      legend: "count",
      legendOffset: -40,
      legendPosition: "center",
    },
    enableGridX: true,
    enableGridY: true,
    lineWidth: 2,
    data: [
      {
        id: "japan",
        color: "hsl(310,70%,50%)",
        data: [
          { x: "plane", y: 161 },
          { x: "helicopter", y: 217 },
          { x: "boat", y: 88 },
          { x: "train", y: 13 },
          { x: "subway", y: 258 },
          { x: "bus", y: 258 },
          { x: "car", y: 200 },
          { x: "moto", y: 244 },
          { x: "bicycle", y: 118 },
          { x: "horse", y: 220 },
          { x: "skateboard", y: 31 },
          { x: "others", y: 299 },
        ],
      },
      {
        id: "france",
        color: "hsl(35,70%,50%)",
        data: [
          { x: "plane", y: 70 },
          { x: "helicopter", y: 18 },
          { x: "boat", y: 298 },
          { x: "train", y: 163 },
          { x: "subway", y: 13 },
          { x: "bus", y: 156 },
          { x: "car", y: 30 },
          { x: "moto", y: 78 },
          { x: "bicycle", y: 60 },
          { x: "horse", y: 33 },
          { x: "skateboard", y: 75 },
          { x: "others", y: 100 },
        ],
      },
      {
        id: "us",
        color: "hsl(276,70%,50%)",
        data: [
          { x: "plane", y: 143 },
          { x: "helicopter", y: 241 },
          { x: "boat", y: 31 },
          { x: "train", y: 140 },
          { x: "subway", y: 120 },
          { x: "bus", y: 55 },
          { x: "car", y: 134 },
          { x: "moto", y: 73 },
          { x: "bicycle", y: 193 },
          { x: "horse", y: 6 },
          { x: "skateboard", y: 26 },
          { x: "others", y: 97 },
        ],
      },
      {
        id: "germany",
        color: "hsl(27,70%,50%)",
        data: [
          { x: "plane", y: 283 },
          { x: "helicopter", y: 168 },
          { x: "boat", y: 93 },
          { x: "train", y: 239 },
          { x: "subway", y: 71 },
          { x: "bus", y: 121 },
          { x: "car", y: 189 },
          { x: "moto", y: 245 },
          { x: "bicycle", y: 242 },
          { x: "horse", y: 234 },
          { x: "skateboard", y: 231 },
          { x: "others", y: 223 },
        ],
      },
      {
        id: "norway",
        color: "hsl(145,70%,50%)",
        data: [
          { x: "plane", y: 169 },
          { x: "helicopter", y: 270 },
          { x: "boat", y: 289 },
          { x: "train", y: 134 },
          { x: "subway", y: 170 },
          { x: "bus", y: 144 },
          { x: "car", y: 234 },
          { x: "moto", y: 9 },
          { x: "bicycle", y: 257 },
          { x: "horse", y: 247 },
          { x: "skateboard", y: 95 },
          { x: "others", y: 25 },
        ],
      },
    ],
  };